create schema if not exists users_roles_exemple;

set search_path = users_roles_exemple;

DROP TABLE IF EXISTS users_roles_exemple."ROLES" CASCADE;
CREATE TABLE users_roles_exemple."ROLES"
(
    roleid int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "roleName" VARCHAR(10) COLLATE pg_catalog."default",
    description text COLLATE pg_catalog."default",
    CONSTRAINT "ROLES_pkey" PRIMARY KEY (roleid)
);
DROP TABLE IF EXISTS users_roles_exemple."USERS" CASCADE;
CREATE TABLE users_roles_exemple."USERS"
(
    userid int NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    "Nom" VARCHAR(25) COLLATE pg_catalog."default",
    "Prenom" VARCHAR(25) COLLATE pg_catalog."default",
    commentaire text COLLATE pg_catalog."default",
    CONSTRAINT "USERS_pkey" PRIMARY KEY (userid)
);
DROP TABLE IF EXISTS users_roles_exemple.users_roles CASCADE;
CREATE TABLE users_roles_exemple.users_roles
(
    roleid int NOT NULL,
    usersid INT NOT NULL,
    CONSTRAINT users_roles_pkey PRIMARY KEY (roleid, usersid),
    CONSTRAINT "roleFK" FOREIGN KEY (roleid)
        REFERENCES users_roles_exemple."ROLES" (roleid),
    CONSTRAINT "userFK" FOREIGN KEY (usersid)
	    REFERENCES users_roles_exemple."USERS" (userid)
);

DROP TABLE IF EXISTS users_roles_exemple."DONNEBRUTE" CASCADE;
CREATE TABLE users_roles_exemple."DONNEBRUTE"
(
	"Nom" VARCHAR(25) COLLATE pg_catalog."default",
    "Prenom" VARCHAR(25) COLLATE pg_catalog."default",
    "roleName" VARCHAR(10) COLLATE pg_catalog."default"
);


